on:
  schedule:
    - cron: '*/15 * * * *'

name: Auto post (15 mins)

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Tweet
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACC_COVID19NEARME_TKN: ${{ secrets.TWITTER_ACC_COVID19NEARME_TKN }}
        TWITTER_ACC_COVID19NEARME_SEC: ${{ secrets.TWITTER_ACC_COVID19NEARME_SEC }}
      run: |
        yarn
        node index.js
