on:
  schedule:
    - cron: '*/15 * * * *'

name: Auto post (15 mins)

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Tweet
      run: |
        yarn
        node index.js
