on:
  workflow_dispatch:
    inputs:
      ignore:
        description: 'Leave empty'

name: Manual post

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Tweet
      run: |
        yarn
        node index.js
